site_name: Howard Heaton
site_description: Howard specializes in the creation and application of optimization algorithms for big data problems, including for deep learning applications. 

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo-v3-light.png
  favicon: assets/logo-v3-dark.png   
  features:
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate 

plugins: [] # required to remove search bar

extra:
  homepage: https://typalacademy.com
  social:       
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/howard-heaton/
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TypalAcademy    
    - icon: simple/substack
      link: https://substack.com/@howardheaton 
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/TypalAcademy         

 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg      

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2023 Howard Heaton
