site_name: Howard Heaton
site_description: Howard specializes in the creation and application of optimization algorithms for big data problems, including for deep learning applications. 

plugins:
  - mkdocstrings
  - social:
      cards_color:
        fill: "#7086DF" 
        text: "#FFFFFF"      

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo-v3-light.png
  favicon: assets/logo-v3-dark.png   
  features:
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate 



extra:
  homepage: https://typal.academy
  social:
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/TypalAcademy         
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/typalacademy  
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TypalAcademy    
    - icon: simple/substack
      link: https://substack.com/@howardheaton    


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2023 Howard Heaton
  <br>
  <a href="#__consent">Cookie Settings</a>
