site_name: Howard Heaton
site_description: Personal site for Howard Heaton, a specialist in the development of optimization algorithms for big data

theme:
  name: material
  logo: assets/logo-v3-light.png
  favicon: assets/logo-v3-dark.png   
  features:
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate 

plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      theme: dark
      include_source: True
      include: ["*.ipynb"]
  - social:
      cards_color:
        fill: "#7086DF" 
        text: "#FFFFFF"      

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/TypalAcademy  
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TypalAcademy
    - icon: fontawesome/brands/vimeo
      link: https://vimeo.com/TypalAcademy    
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TypalAcademy    
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they are searching for. Your consent helps make this site better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
  analytics:
    provider: google
    property: G-5080H11KV0        


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2023 Howard Heaton
  <br>
  <a href="#__consent">Cookie Settings</a>
